# Drinks
def create_lists():
    drinks = [
        "Iced Coffee",
        "Freshly Brewed Black Tea",
        "Classic Cola",
        "Lemonade",
        "Sparkling Water",
        "Mojito",
        "Strawberry Daiquiri",
        "Cappuccino",
        "Espresso",
        "Mango Lassi",
        "Green Smoothie",
        "Virgin Piña Colada",
        "Orange Juice",
        "Ginger Ale",
        "Iced Green Tea",
        "Cranberry Spritzer",
        "Chocolate Milkshake",
        "Hot Chocolate",
        "Cucumber-Mint Cooler",
        "Pomegranate Martini",
        "Long Island Iced Tea",
        "Blueberry Lemonade",
        "Raspberry Iced Tea",
        "Chai Latte",
        "Mango Iced Tea"
    ]

    # Appetizers
    appetizers = [
        "Spinach Artichoke Dip",
        "Bruschetta",
        "Mozzarella Sticks",
        "Shrimp Cocktail",
        "Stuffed Mushrooms",
        "Chicken Wings",
        "Spring Rolls",
        "Fried Calamari",
        "Sliders",
        "Nachos",
        "Garlic Bread",
        "Crispy Onion Rings",
        "Caprese Salad",
        "Dumplings",
        "Potato Skins",
        "Deviled Eggs",
        "Loaded Fries",
        "Bacon-Wrapped Scallops",
        "Mini Tacos",
        "Cheese Platter"
    ]

    # Entrees
    entrees = [
        "Grilled Steak",
        "Roast Chicken",
        "Salmon Fillet",
        "Pasta Carbonara",
        "Burger with Fries",
        "Sushi Platter",
        "Chicken Parmesan",
        "Shrimp Scampi",
        "Vegetable Stir-Fry",
        "Beef Stir-Fry",
        "Lobster Tail",
        "Rack of Ribs",
        "Eggplant Parmesan",
        "Seafood Paella",
        "Fettuccine Alfredo",
        "Tandoori Chicken",
        "Filet Mignon",
        "Shrimp and Grits",
        "Vegan Curry",
        "Mushroom Risotto",
        "Pad Thai",
        "Fish and Chips",
        "Taco Platter",
        "Vegetable Lasagna",
        "Grilled Veggie Wrap",
        "Stuffed Bell Peppers",
        "Pork Tenderloin",
        "Gourmet Pizza",
        "BBQ Pulled Pork Sandwich",
        "Steak Fajitas",
        "Chicken Tenders",
        "Sesame Crusted Tuna",
        "Lamb Chops",
        "Spaghetti Bolognese",
        "Grilled Portobello",
        "Sashimi Platter",
        "Cajun Jambalaya",
        "Butter Chicken",
        "Hawaiian Poke Bowl",
        "Pho Noodle Soup",
        "Beef Tacos",
        "Butternut Squash Ravioli",
        "Sautéed Shrimp",
        "Vegan Burger",
        "Chicken Shawarma"
    ]

    # Desserts
    desserts = [
    "Chocolate Lava Cake",
    "New York Cheesecake",
    "Tiramisu",
    "Apple Pie",
    "Crème Brûlée",
    "Brownie Sundae",
    "Fruit Parfait",
    "Churros",
    "Red Velvet Cupcake",
    "Panna Cotta",
    "Lemon Sorbet",
    "Key Lime Pie",
    "Caramel Flan",
    "Banana Split",
    "Chocolate Chip Cookies",
    "Molten Chocolate Soufflé",
    "Strawberry Shortcake",
    "Berry Crumble",
    "Ice Cream Sundae",
    "Coconut Macaroon"
]
